spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: testuser
    password: gbvsfy7z!
    url: jdbc:mysql://localhost:3306/board

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100